from typing import Optional
from src.clients.clients import get_openai_client
from src.tests.response_models import StandardConfirmation


class OpenAIConfirmations:
    def __init__(self, model: Optional[str] = "gpt-4.1-nano"):
        self.model = model
        self.openai_client = get_openai_client()

    def confirm_image_response(self, model_response: str) -> StandardConfirmation:
        system_prompt = (
            f"The following response was generated by an AI model based on image inputs. "
            f"Please confirm if the response describes a vehicle."
        )
        response = self.openai_client.responses.parse(
            model=self.model,
            input=model_response,
            instructions=system_prompt,
            text_format=StandardConfirmation,
        )

        return response.output_parsed

    def confirm_json_structure(self, model_response: str) -> StandardConfirmation:
        system_prompt = (
            "The following response was generated by an AI model. "
            "Please confirm if the response is a valid JSON structure."
            "Also confirm that the JSON lists soccer players with their name, position, country, and skill rating."
            "Ensure there is no additional text outside the JSON."
        )
        response = self.openai_client.responses.parse(
            model=self.model,
            input=model_response,
            instructions=system_prompt,
            text_format=StandardConfirmation,
        )

        return response.output_parsed
