from typing import Optional
import yfinance as yf
from src.clients.clients import get_openai_client
from src.tests.response_models import StandardConfirmation


class OpenAIConfirmations:
    def __init__(self, model: Optional[str] = "gpt-4.1-nano"):
        self.model = model
        self.openai_client = get_openai_client()

    def confirm_image_response(self, model_response: str) -> StandardConfirmation:
        system_prompt = (
            f"The following response was generated by an AI model based on image inputs. "
            f"Please confirm if the response describes a vehicle."
            "If the model response does not include a description of a vehicle, mark confirmed as false."
        )
        response = self.openai_client.responses.parse(
            model=self.model,
            input=model_response,
            instructions=system_prompt,
            text_format=StandardConfirmation,
        )

        return response.output_parsed

    def confirm_json_structure(self, model_response: str) -> StandardConfirmation:
        system_prompt = (
            "The following response was generated by an AI model. "
            "Please confirm if the response is a valid JSON structure."
            "Also confirm that the JSON lists soccer players with their name, position, country, and skill rating."
            "Ensure there is no additional text outside the JSON."
        )
        response = self.openai_client.responses.parse(
            model=self.model,
            input=model_response,
            instructions=system_prompt,
            text_format=StandardConfirmation,
        )

        return response.output_parsed

    def fetch_stock_data(self, ticker_symbol: str):
        try:
            ticker = yf.Ticker(ticker_symbol)
            stock_info = ticker.info
            return stock_info.get("currentPrice", None)

        except Exception as e:
            return {"error": str(e)}

    def confirm_tool_calling_response(
        self, model_response: str
    ) -> StandardConfirmation:
        stock_price = self.fetch_stock_data("META")
        system_prompt = (
            "The following response was generated by an AI model using tool calling. "
            "Please confirm that the response includes the current stock price of META."
            f"Please confirm that the stock price in the response is within a few dollars of ${stock_price}."
        )
        response = self.openai_client.responses.parse(
            model=self.model,
            input=model_response,
            instructions=system_prompt,
            text_format=StandardConfirmation,
        )

        return response.output_parsed
